pipeline {
    parameters {
        string(name: 'GIT_REPO_NAME', defaultValue: 'https://github.com/maifujalam/k8s_aws.git', description: 'Enter the git repo URL')
        string(name: 'GIT_BRANCH_NAME', defaultValue: 'master', description: 'Enter the branch name')
        string(name: 'APP_FOLDER_PATH', defaultValue: 'EvictedPodCleaner', description: 'Folder containing the Dockerfile')
        string(name: 'APP_NAME', defaultValue: 'evicted-pod-cleaner', description: 'App name')
        string(name: 'DOCKER_REPOSITORY_NAME', defaultValue: 'skmaifujalam/evicted-pod-cleaner', description: 'Docker repository Name')
    }
    agent {
        kubernetes {
            yaml '''
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
'''
        }
    }

    stages {
        stage('Git Checkout') {
            steps {
                container(name: 'kaniko') {
                    checkout([$class: 'GitSCM',
                        branches: [[name: "${params.GIT_BRANCH_NAME}"]],
                        userRemoteConfigs: [[url: "${params.GIT_REPO_NAME}"]]
                    ])
                }
            }
        }
        stage('Sleeper') {
            steps {
                container(name: 'kaniko',shell: '/busybox/sh') {
                  sh '''#!/busybox/sh
                    echo "FROM jenkins/inbound-agent:latest" > Dockerfile
                    /kaniko/executor --context `pwd` --destination darinpope/hello-kaniko:latest
                  '''
                }
            }
        }
    }

}
