pipeline {
    parameters {
        string(name: 'GIT_REPO_NAME', defaultValue: 'https://github.com/maifujalam/k8s_aws.git', description: 'Enter the git repo URL')
        string(name: 'GIT_BRANCH_NAME', defaultValue: 'master', description: 'Enter the branch name')
        string(name: 'APP_FOLDER_PATH', defaultValue: 'EvictedPodCleaner', description: 'Folder containing the Dockerfile')
        string(name: 'APP_NAME', defaultValue: 'evicted-pod-cleaner', description: 'App name')
        string(name: 'DOCKER_REPOSITORY_NAME', defaultValue: 'skmaifujalam/evicted-pod-cleaner', description: 'Docker repository Name')
    }
    agent {
        kubernetes {
            yaml """
                apiVersion: v1
                kind: Pod
                metadata:
                  name: kaniko
                spec:
                  containers:
                  - name: kaniko
                    image: gcr.io/kaniko-project/executor:latest
                    command: ["/kaniko/executor"]
                    args: ["--dockerfile=/workspace/Dockerfile",
                            "--context=dir:///workspace",
                            "--destination=${DOCKER_REPOSITORY_NAME}:${BUILD_NUMBER}"]
                    volumeMounts:
                      - name: kaniko-secret
                        mountPath: /kaniko/.docker
                      - name: dockerfile-storage
                        mountPath: /workspace
                  restartPolicy: Never
                  volumes:
                    - name: kaniko-secret
                      secret:
                        secretName: regcred
                        items:
                          - key: .dockerconfigjson
                            path: config.json
                    - emptyDir:
                        medium: ""
                      name: "dockerfile-storage"
        """
        }
    }

    stages {
        stage('Git Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: "${params.GIT_BRANCH_NAME}"]],
                    userRemoteConfigs: [[url: "${params.GIT_REPO_NAME}"]]
                ])
            }
        }
    }

}
