pipeline {
    agent any
    environment {
        HELM_CHART_DIR = 'helm-chart-directory'
        HELM_VALUES_FILE = 'values.yaml'
    }
    parameters {
        string(name: 'GIT_REPO_NAME', defaultValue: 'https://github.com/maifujalam/k8s_aws.git', description: 'Enter the git remote name')
        string(name: 'GIT_BRANCH_NAME', defaultValue: 'master', description: 'Enter the branch name to pull from')
        string(name: 'ARGO_APP_FOLDER_PATH', defaultValue: 'k8s/argocdApplication', description: 'Enter the folder path name which to be helm build')
        string(name: 'ARGO_APP_NAME', description: 'Enter ArgoCD App Name to deploy')
        string(name: 'ARGO_APP_VERSION', defaultValue: '1.0.0',description: 'Enter ArgoCD App Version to deploy')
    }
    stages {
//         stage('Checkout') {
//             steps {
//                 // Checkout code from SCM (Git, etc.)
//                 checkout scm
//             }
//         }

        stage('Create argocd application') {
            steps {
                script {
                    sh """
                        echo "Looking for existing app"
                        ls -al
                    """
                }
            }
        }

        stage('Push Argocd Application') {
            when {
                expression {
                    // Proceed only if the previous step was successful
                    return currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                script {
                    // Build and package the Helm chart
                    sh """
                        helm lint ${HELM_CHART_DIR}
                        helm package ${HELM_CHART_DIR}
                    """
                }
            }
        }

        stage('Sync Argocd Application') {
            when {
                expression {
                    return currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                script {
                    // Push the packaged chart to a Helm repository (if required)
                    // Replace this with actual commands if you're pushing to a repository
                    echo "Pushing Helm chart to repository"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished"
        }
        failure {
            echo "Pipeline failed"
        }
        success {
            echo "Helm chart build successful"
        }
    }
}
