apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-raw
spec:
  containers:
  - name: jenkins-agent-raw
    image: gcr.io/jenkins-agent-raw-project/executor:v1.20.0
    imagePullPolicy: IfNotPresent
    args: ["--dockerfile=/workspace/Dockerfile",
            "--context=dir://workspace",
            "--insecure-registry=docker-registry:5000",
            --destination=ubuntu-local:1]
    volumeMounts:
      - name: pvc-jenkins-agent-raw
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: pvc-jenkins-agent-raw
      persistentVolumeClaim:
        claimName: pvc-jenkins-agent-raw